// Code generated by Kitex v0.4.4. DO NOT EDIT.

package messageservice

import (
	"context"
	"douyin/code_gen/kitex_gen/messageproto"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateMessage(ctx context.Context, Req *messageproto.CreateMessageReq, callOptions ...callopt.Option) (r *messageproto.CreateMessageResp, err error)
	GetComments(ctx context.Context, Req *messageproto.GetMessageListReq, callOptions ...callopt.Option) (r *messageproto.GetMessageListResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kMessageServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kMessageServiceClient struct {
	*kClient
}

func (p *kMessageServiceClient) CreateMessage(ctx context.Context, Req *messageproto.CreateMessageReq, callOptions ...callopt.Option) (r *messageproto.CreateMessageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateMessage(ctx, Req)
}

func (p *kMessageServiceClient) GetComments(ctx context.Context, Req *messageproto.GetMessageListReq, callOptions ...callopt.Option) (r *messageproto.GetMessageListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetComments(ctx, Req)
}
